# Generated by Django 4.2.6 on 2023-10-27 14:02

from django.db import migrations
from django.db import models


def forward(apps, schema_editor):
    my_model = apps.get_model('db', 'Post')
    posts = my_model.objects.all()
    for index, post in enumerate(posts):
        post.title = f"{post.title}+{index}"
        post.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(unique=True),
        ),
    ]
