# Generated by Django 4.2.6 on 2023-10-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
    ]
