# Generated by Django 4.2.6 on 2023-10-27 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_title_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='base_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
