# Generated by Django 4.2.6 on 2023-10-27 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_post_base_id_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='base_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
