# Generated by Django 4.2.6 on 2023-10-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_user_post_created_by_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
