version: '3.7'
services:
  db:
    image: postgres:16
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      - django_orm_standalone

networks:
  django_orm_standalone: